### ISSUE TITLE
[0.4.4] Could not compile 'sysinfo' on Windows 10

### ISSUE THREAD

**Issue by tommywalkie** [ClementTsang/bottom#173]
## Describe the bug

`bottom v0.4.4` fails to compile on Windows (`rustc 1.41.1`) when trying to compile `sysinfo v0.14.2`

```sh
error: attributes are not yet allowed on `if` expressions
  --> C:\...\sysinfo-0.14.10\src\utils.rs:27:5
   |
27 |     #[allow(clippy::identity_conversion)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
error: could not compile `sysinfo`
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bottom v0.4.4`
```

## To reproduce

_Steps on how to reproduce the behaviour:_

1. `cargo install bottom`

## Platform

_If relevant, please provide information on:_

**Operating System:** Windows 10

**Terminal:** Windows Terminal

**Shell:** Powershell

**bottom version (use `btm -V`):** 0.4.3

**Any other relevant information (more details are always good!):**

**Comment by ClementTsang** [comment]
Ah.  I think I know what's wrong... it seems to be trying to use a newer version of `sysinfo` from `Cargo.lock`.  I'll see if I can fix that...

**Comment by tommywalkie** [comment]
@ClementTsang I was kinda thinking the same, but was not sure at all because of the successful Windows-based `rustc 1.40.0` Travis CI [pipeline logs](https://travis-ci.com/github/ClementTsang/bottom/jobs/357780578#L260).

**Comment by ClementTsang** [comment]
It's probably because (AFAIK) `cargo install` deals with `Cargo.lock`, which is... sometimes a bit confusing for me.  It didn't seem to respect what I had put in `Cargo.toml` for `sysinfo`, and the newer version it's pulling seems to break on older Rust versions by using a new feature of Rust.  I'll put out a patch so it works on what I specified was the MSRV, but that'll take some time.

If you want an immediate fix it seems that if I use stable Rust (v1.44.1) it compiles fine via `cargo install bottom`.  Or, manually build by cloning and doing ``cargo install --path . --locked`` in the repo, which does seem to work even for v1.40.0.

I made the mistake of *only* testing installing via cargo on the newest stable version of Rust in my pipeline when I'm deploying, unfortunately (gonna try to remedy that).  Sorry!

**Comment by tommywalkie** [comment]
@ClementTsang It's fine, you can take your time 👍 But thanks a lot for providing detailed explanation and workarounds !

**Comment by ClementTsang** [comment]
@tommywalkie Deployed 0.4.5.  https://github.com/rust-lang/cargo/issues/7169 explained some things, you would still need to do 

```bash
cargo install bottom --locked
```

to get it to work and adhere to the lock file (otherwise it grabs the wrong version of sysinfo), and it builds for me even on 1.40.0 on Linux.  I haven't got around to testing it on Windows but I would imagine it should work.

If anything still isn't working please let me know!

**Comment by tommywalkie** [comment]
@ClementTsang Can confirm I could compile `bottom v0.4.5` with the mentionned command, thanks for the fix 👍
