### ISSUE TITLE
Tree process view

### ISSUE THREAD

**Issue by lespea** [ClementTsang/bottom#184]
## Describe the feature request

It would be great if we could get a tree view of the process listing; this would obviously disable any other sorting mechanisms.  
Thinking of how filtering might work... I can think of two approaches.

1. Display only the items that match the filters, most likely removing all of the leading spaces/indent marks
2. Darken the text of non-matching parent items so the matched items would easily stand out but you could still see where they live in the hierarchy

## Additional context/details

I've always found this gives a lot of context around what is happening on the machine and use it almost exclusively in similar programs (such as htop)

**Comment by ClementTsang** [comment]
@lespea out of curiosity, which approach towards filtering do you prefer?  Both are doable and pretty easy to implement for what it's worth so that isn't really too much of a concern.

A third idea I thought of randomly was kinda combining both - prune out any branches that have absolutely zero children that match the search, but keep any branches that have at least one child that matches the search and gray out all entries within the branch that don't match.  This allows you to still preserve the tree structure for relevant branches, while removing any irrelevant branches.

I'm also open to any other suggestions, so feel free to let me know.

**Comment by lespea** [comment]
Yeah that's something similar to what I had in mind... looks great!

Just another thought to throw out there, in windows (process hacker) you can collapse a tree entry and it will "add up" the sub entries into the parent.  So it would add up all the cpu/mem usage of child processes, add it to it's own, and display that.  maybe if you were navigating you could hit like space bar or something and it would collapse it?  I don't think that's something that would be required just wanted to point out other successful strategies.

But honestly if you were to ship what you have in those screenshots that would meet 99% of my needs.

Great work!

**Comment by Narice** [comment]
Is it possible to get also the children to be shown when filtering?
In htop sometimes I'm searching for the parent process to find the child process that is stalling the parent one.
(Primary used for when something goes wrong in emacs)

**Comment by ClementTsang** [comment]
Yes, that's something I'm working on adding since I also don't like the current behaviour. Also, in the future, please open a new issue.

**Comment by Narice** [comment]
Oh nice!
Do you want me to open an issue to track this feature?

**Comment by ClementTsang** [comment]
@Narice filed an issue here: #668

Feel free to add to it if you want.

**Comment by Narice** [comment]
Oh thank you! I'll follow the linked issue then.
