### ISSUE TITLE
What is the different between "bottom_source_code.tar.gz" and "Source code (tar.gz)" on Release Page?

### ISSUE THREAD

**Issue by KSXGitHub** [ClementTsang/bottom#28]
What is the different? Why is `bottom_source_code.tar.gz` necessary?

![image](https://user-images.githubusercontent.com/11488886/75253551-54e1e480-5811-11ea-8c43-dc7120bfea66.png)

[release page](https://github.com/ClementTsang/bottom/releases/tag/0.2.1)

**Comment by ClementTsang** [comment]
Sorry about the confusing name!  ``Source code`` is the one automatically generated by GitHub on a release, and it contains everything in the repo upon releasing - including stuff that is not required for building from source, like the GIF from the readme in `assets`, contribution/bug report files, sample configs, etc.  

``bottom_source_code.tar.gz`` is made by me on release (well by Travis) to only contain the required files to build from source (and some stuff like Licenses).  This is mostly used for building from AUR since that builds from source, rather than using a pre-built binary.

Hope that answers the question.
