### ISSUE TITLE
Populate a default config file

### ISSUE THREAD

**Issue by shilangyu** [ClementTsang/bottom#37]
## Describe the feature request

Perhaps it is a good idea to create a default config file (same as the one that is bundled into release) in the config path (as specified [here](https://github.com/ClementTsang/bottom/blob/master/docs/config.md#default-config-locations)) if it does not exist? 

## Additional context/details

Why it would be beneficial:
- no more need for bundling the default config file with a release (single executable ftw)
- the config file will anyways end up in this path, so why not put it automatically
- easier to get started, just run `btm` once and you can go straight to configuring with lets say `vim ~/.config/bottom/bottom.toml`

**Comment by shilangyu** [comment]
If you accept contributions I would like to tackle this issue, seems like a good first issue

**Comment by shilangyu** [comment]
The approach I have been using in my projects that use config files is the following:
- the program starts
- looks for a config file
  - if it exists, load the config
  - if it does not exist, create it with a ready config that has comments around each field (similar to [alacritty](https://github.com/alacritty/alacritty)) and load it
- overwrite the config with commandline flags
- use defaults for missing fields

What do you think?

**Comment by ClementTsang** [comment]
> overwrite the config with commandline flags

While I like the idea behind this, this part is kinda 50/50 for me.  I'm just not 100% on setting values for the user without them explicitly knowing that they're set, especially since if an option is set to true on the config file, then there's no way to actually turn the thing off from the command line - only on.

So either notifying the user what values are set, or just (imo the easier solution I guess) leaving it default entirely if we create one is probably what I would rather do.

The rest of it I like though.

**Comment by shilangyu** [comment]
What I meant by _overwrite the config with commandline flags_ is what is already currently implemented. If my config file says the temperature should be Kelvin, but I run bottom with `btm -c` it will prioritize the Celsius flag and show the temperature in Celsius

**Comment by ClementTsang** [comment]
Ah, okay.  Thought you meant something like, if you run say ``btm -a`` with no config file it would generate a config file with the ``average_cpu`` flag set to true.

Looks good then!
