### ISSUE TITLE
CPU utilization is not shown for certain processes on macOS

### ISSUE THREAD

**Issue by up-to-you** [ClementTsang/bottom#380]
## Describe the bug

Comparing to built-in Activity Monitor on Mac - bottom doesn't show CPU utilization for such processes like KAV (Kaspersky), WindowServer. Whenever Activity Monitor show CPU util near 100% (single core) for KAV / WindowServer or Activity Monitor itself - bottom displays 0.0%-0.1% or statically exactly 0.0%.

## To reproduce

redundant

## bottom version

0.5.6

## bottom config file (if used)

Default, not changes

## Installation method

brew

### Operating system, OS version, and architecture

Macos, Catalina

### Terminal (i.e. urxvt, kitty, etc.)

Alacritty

### Shell (i.e. zsh, bash, etc.)

zsh

### Rust version

1.48.0

**Comment by ClementTsang** [comment]
Out of curiosity, does a program like htop properly show the processes you're looking for?

Also, full disclaimer, I rely on another library for processes for macOS and Windows, so I may not exactly be able to fix this here.

**Comment by ClementTsang** [comment]
@up-to-you could you also see if you get this problem if you run `btm` with `sudo`?  This is an issue that I know affects a similar program, htop, as well, since otherwise we can't access some processes.

If I do so on my Catalina machine and say, open Firefox, I see a sudden spike in usage on both Activity Monitor and bottom for the WindowServer entry, for example.

**Comment by up-to-you** [comment]
Yep ! Thats it! If i'm running `sudo btm` i see KAV process utilization. But, there is tiny glitch (don't know if i can name it a bug), that i see zero utilization of WindowServer without `sudo` and some little spikes (natural, truthful) with `sudo`.

**Comment by ClementTsang** [comment]
Cool, I should probably add to the documentation that `sudo` might be needed on macOS for proper reporting.

---

If the CPU usage doesn't match something like Activity Monitor, I'm fairly certain that's expected - the way we calculate and report CPU usage is different.  For example, Activity Monitor, from my understanding, can report over 100% usage due to how they report core usage.  bottom doesn't do that, so there may be some difference.

Unless it's obviously inaccurate - for example, if Activity Monitor is reporting like 300% usage while bottom is reporting 0% usage - I think it should be fine.

Side note, I might introduce options in the future that allow you to tweak how CPU usage is reported per-process, because there's a bunch of ways you can do it, but that's out of scope for this issue in my opinion.

**Comment by ClementTsang** [comment]
Added documentation a few days ago mentioning requiring elevated access for macOS: d8d72d060d4bd4473bfe769673a2227bda948c97

Going to close this for now.

**Comment by petrisch** [comment]
Just for future searchers. This is the same on Windows at least for me.

**Comment by ClementTsang** [comment]
@petrisch is this solved by using admin mode? And are you running on Windows or something like WSL?
