### ISSUE TITLE
The graph of the cpu and RAM does not show anything in WSL2. The temperature sensors are not shown either.

### ISSUE THREAD

**Issue by jesusfj710** [ClementTsang/bottom#388]
### Question

_Is there any incompatability between `bottom` and WSL2 in Windows 10?_

![image](https://user-images.githubusercontent.com/71794881/104129540-9b2e2c80-536c-11eb-880f-e00590cd5a19.png)
![image](https://user-images.githubusercontent.com/71794881/104129545-9c5f5980-536c-11eb-8a0d-25b6259de55d.png)

**Comment by ClementTsang** [comment]
Not sure, haven't tested this.

It's possible there might be problems given how I understand WSL2 works.  I'll get back to you after testing it a bit.

**Comment by ClementTsang** [comment]
Alright, can somewhat replicate this.  Notes so far:

- Temperature sensors not working on WSL isn't too surprising, [the](https://github.com/GuillaumeGomez/sysinfo#linux-on-docker--windows-subsystem-for-linux-wsl) library I use explicitly mentions they won't work when working with WSL/Docker.  I'll mention this on my own README.
- CPU graphs seem to be fine for me... cores directly match when comparing bottom and Task Manager.
![image](https://user-images.githubusercontent.com/34804052/104132682-e6d0de00-534c-11eb-8a02-d5c9a66561a8.png)
- Memory seems to not be showing up at all, I'll look at this.  Seems to be a bug with how I get total memory.
- Not sure why networks isn't working at all, I'll take a look.
- Processes being limited makes sense, htop has a similar issue.

**Comment by ClementTsang** [comment]
I just took a peek at htop: 
![image](https://user-images.githubusercontent.com/34804052/104133568-5e553c00-5352-11eb-81b9-d637f32d6540.png)

and it seems to have the same issue.  I'm guessing this has to do with how WSL2 works, and less with my program specifically... not sure if/how to fix for now.

**Comment by ClementTsang** [comment]
@jesusfj710 Ah, I see now.  It's due to how WSL2 works.

If I stress the *Linux* environment (here I'm just doing a release build of bottom to do so) you can see activity that matches with htop.

![image](https://user-images.githubusercontent.com/34804052/104134596-a7a88a00-5358-11eb-9052-b2d8afb9f92f.png)

The problem is that it won't match with Task Manager, which will report usage of the Windows environment and the WSL2 environment.  But this makes sense (I think) - as I understand it, WSL2 is based on virtualization, which would mean it's like running `bottom` on top of a VM - which makes sense if it can't see CPU and memory usage of the host machine.

The temp sensors not working is annoying, but this is, as mentioned earlier, something I can't fix myself.

**Comment by ClementTsang** [comment]
@jesusfj710 Ah, I see now.  It's (I think) due to how WSL2 works.

If I stress the *Linux* environment (here I'm just doing a release build of bottom to do so) you can see activity that matches with htop.

![image](https://user-images.githubusercontent.com/34804052/104134734-93b15800-5359-11eb-80b3-52d024794494.png)

![image](https://user-images.githubusercontent.com/34804052/104134742-990ea280-5359-11eb-9900-2f3cd9aa8356.png)




The problem is that it won't match with Task Manager, which will report usage of the Windows environment and the WSL2 environment.  But this makes sense (I think) - as I understand it, WSL2 is based on virtualization, which would mean it's like running `bottom` on top of a VM - which makes sense if it can't see CPU and memory usage of the host machine.

The temp sensors not working is annoying, but this is, as mentioned earlier, something I can't fix myself.

**Comment by jesusfj710** [comment]
Thanks for taking a look. Sorry to answer so late, I thought I had the notifications active.

I forgot to mention that I was using WSL2.

As far as I know, with WSL2, the operating system is not virtualised (in this case, Ubuntu 20.04), but the WSL2 kernel has access to the Windows 10 kernel, but that's something I still can't understand. That's why I thought that all CPU usage should be reported in `btm` as well as `htop`, but that's still what you're saying.

I'll try to find more information about it and if I make myself clear, I'll put it here in case it's useful for you.

Thanks for everything again!

**Comment by ClementTsang** [comment]
@Mateus-M-Reis WSL1 and WSL2 are referring to [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10), a way of running Linux on Windows.

If you're having a Linux-specific bug please open a new bug report.
