### ISSUE TITLE
btrfs disk io

### ISSUE THREAD

**Issue by asonix** [ClementTsang/bottom#436]
### Describe the feature request
Disk IO for btrfs mounts currently shows up as N/A, It would be nice for reads & writes to be monitored for this filesystem

**Comment by ClementTsang** [comment]
Hmm... I just setup an Opensuse VM which comes with btrfs by default, and it seems to show fine:

![image](https://user-images.githubusercontent.com/34804052/111057498-fad0b300-8455-11eb-877f-9f6dc26bdba4.png)

Are there any other details in regards to your disk setup that I should know about, such as encryption?

**Comment by asonix** [comment]
Ah yes, I thought it was because of btrfs, but all of my btrfs drives are on top of LUKS

**Comment by ClementTsang** [comment]
Yeah, encryption throws a bit of a wrench from my experience for I/O due to how the drives are reported.

Could you try the nightly build which contains a fix for some encrypted setups and see if it fixes your problem?  A similar problem was reported here (https://github.com/ClementTsang/bottom/issues/419) and it should work now.

**Comment by asonix** [comment]
The nightly build seems to work on all my devices, thank you!
